language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  provider: npm
  email: sentialx@gmail.com
  api_key:
    secure: h6xrsaLvgUrxQyOorGL81LQjH8Ak9omor4V1ZdTqHhkLPfriwEFlAEXfCRHwhqS82InkJrMZOyGZgbVVPpEbhX+A9whGSq5A5YNuvPrYO/QbRo8KhimW8hHucg5VMsj/WtPhcPLiuzJ4LFagzVcfhSaJ9nzDvhn4fcPyJ42G5KKuBdSnhX+Vv+QImWylX7GEGr/JIFAVMi1e94iF1GEhqJnMoRrt5sl8v3ElVdg3Ql6OVYA81kVwGk3VLkIHxaAs55dXpXgoajcAKyFqeP6+dd+v6BHslM6teCPf3c0qTcQfEOmyhmP+apdhq4ZF/LesOuEO8h6AeSLOYLw02PDOxHeZPj0BXkJ0mE1zKt+VX9UnXaZewrSAzJPcFlBTDJLY066fduW/nDSyBX3JI2oNEJkmbgHlPlofibeau5dZagBQpdx4DrywQO4AGuHhL/zA8bdwSMi7Dyt7KsPMvt5aWUk7TzGtxmF5nqZ8ydYSlrG7Dr7BreNAi3xqGNJ+5bFRJsBg42839KHXhN7myxopM1HYTAAj+wkvkTz2UjpDnzN2Y2dsaryf1RQQbylTbTme+XdNj2FEiYAfOZkM9tMm/tdz26vwrN9K4WAIa1r09liGlYw1Qy5fTzPGmuVXEJNwvW732XQYWUfFPGqegr+Wuk/vUAI1zC+vuWpG9vrjh4k=
  on:
    repo: wexond/wexond-package-manager
