language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: sentialx@gmail.com
  on:
    repo: wexond/wexond-package-manager
  api-key:
    secure: UUfFbN0YiRd1xLZVeIdZRuur4/KTjgm2X9F3Suto/TgqEblnTcjuI9hdfH8sJnttne3TeFgFXeFMWMAi5Kc9pNdue35LVPD53m6IMcwSYsBPoaQUdIdXqIf6VibuJzBThSPcNJLTQLaCzmE55a5glS2vuVH0A5IESqG4yEjwHdPleUjakNohiETNktZok2SaoICFacMXpP1VFnNPNDN4gF0cFrAUnHOYVISD/Cgbf/T//GWqzfTzQoISx9BDdSSs3JjwtfZCtpRF4kI6l1bTc8UFPPX45lzG1mzPd1hGVVox+I00alnPiIahGKyLTA/lzFGha2VilF+VEOWGRPhB94LLH+1fyLfWAXOdmBGDK96Lkym7zuEXgYGrjORE0FatUQbq/ezWFG6AoCfCIwqq3oljiW4LZFTxuq1moKWJOlq9OooY2g8Qub5M5GIQ+So8dNVJgaBULd+LhccfyGPSmdXczjqT/Hyui33BFEF/k1GyyZQqfFt1g00AEPHBTA7fWf4DhAbNwIUF4V0sfauoJukrnou3bsR7dks2kpvAdgYKy1Ooh/M2tMlodBId69yV5cRy67Vq1pnrXdU+f5PGIv4eB+tUb3eYCtF3kxZkY2w1+wXFdeffgKfW8lDc/+7tr8YKbEebNC+Dfa9zMKElSo9wZSzxP2wv9UxAjEtdBZ0=
